-- Configuration based on default vscode-intelephense config https://github.com/bmewburn/vscode-intelephense/blob/master/package.json

return {
  init_options = {
    licenceKey = os.getenv("PHP_INTELEPHENSE_LICENCE")
  },
  settings = {
    intelephense = {
      environment = {
        phpVersion = "7.4.0",
        shortOpenTag = true,
      },
      compatibility = {
        correctForBaseClassStaticUnionTypes = true,
        correctForArrayAccessArrayAndTraversableArrayUnionTypes = true
      },
      diagnostics = {
        embeddedLanguages = true,
        undefinedVariables = true,
        undefinedTypes = true,
        undefinedFunctions = true,
        undefinedConstants = true,
        undefinedClassConstants = true,
        undefinedMethods = true,
        undefinedProperties = true,
        unusedSymbols = true,
        unexpectedTokens = true,
        duplicateSymbols = true,
        argumentCount = true,
        typeErrors = true,
        deprecated = true,
        languageConstraints = true,
        implementationErrors = true,
      },
      telemetry = {
        enabled = false
      },
      completion = {
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = false,
        triggerParameterHints = true,
        maxItems = 100,
      },
      format = {
        enable = true,
        braces = "psr12"
      },
      phpdoc = {
        returnVoid = false,
        textFormat = "snippet",
        classTemplate = {
          summary = "$1",
          tags = {
            "@package ${1:$SYMBOL_NAMESPACE}"
          }
        }
      },
      files = {
        maxSize = 5000000,
        exclude = {
          "**/.git/**",
          "**/.svn/**",
          "**/.hg/**",
          "**/CVS/**",
          "**/.DS_Store/**",
          "**/node_modules/**",
          "**/bower_components/**",
          "**/vendor/**/{Tests,tests}/**",
          "**/.history/**",
          "**/vendor/**/vendor/**"
        }
      },
      stubs = {
        "aerospike",
        "amqp",
        "apache",
        "apcu",
        "ast",
        "bcmath",
        "blackfire",
        "bz2",
        "calendar",
        "cassandra",
        "com_dotnet",
        "Core",
        "couchbase",
        "couchbase_v3",
        "crypto",
        "ctype",
        "cubrid",
        "curl",
        "date",
        "dba",
        "decimal",
        "dio",
        "dom",
        "ds",
        "enchant",
        "Ev",
        "event",
        "exif",
        "fann",
        "FFI",
        "ffmpeg",
        "fileinfo",
        "filter",
        "fpm",
        "ftp",
        "gd",
        "gearman",
        "geoip",
        "geos",
        "gettext",
        "gmagick",
        "gmp",
        "gnupg",
        "grpc",
        "hash",
        "http",
        "ibm_db2",
        "iconv",
        "igbinary",
        "imagick",
        "imap",
        "inotify",
        "interbase",
        "intl",
        "json",
        "judy",
        "ldap",
        "leveldb",
        "libevent",
        "libsodium",
        "libvirt-php",
        "libxml",
        "lua",
        "LuaSandbox",
        "lzf",
        "mailparse",
        "mapscript",
        "mbstring",
        "mcrypt",
        "memcache",
        "memcached",
        "meminfo",
        "meta",
        "ming",
        "mongo",
        "mongodb",
        "mosquitto-php",
        "mqseries",
        "msgpack",
        "mssql",
        "mysql",
        "mysql_xdevapi",
        "mysqli",
        "ncurses",
        "newrelic",
        "oauth",
        "oci8",
        "odbc",
        "openssl",
        "parallel",
        "Parle",
        "pcntl",
        "pcov",
        "pcre",
        "pdflib",
        "PDO",
        "pdo_ibm",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "phpdbg",
        "posix",
        "pspell",
        "pthreads",
        "radius",
        "rar",
        "rdkafka",
        "readline",
        "recode",
        "redis",
        "Reflection",
        "regex",
        "rpminfo",
        "rrd",
        "SaxonC",
        "session",
        "shmop",
        "SimpleXML",
        "snmp",
        "soap",
        "sockets",
        "sodium",
        "solr",
        "SPL",
        "SplType",
        "SQLite",
        "sqlite3",
        "sqlsrv",
        "ssh2",
        "standard",
        "stats",
        "stomp",
        "suhosin",
        "superglobals",
        "svm",
        "svn",
        "sybase",
        "sync",
        "sysvmsg",
        "sysvsem",
        "sysvshm",
        "tidy",
        "tokenizer",
        "uopz",
        "uuid",
        "uv",
        "v8js",
        "wddx",
        "win32service",
        "winbinder",
        "wincache",
        "wordpress",
        "xcache",
        "xdebug",
        "xhprof",
        "xlswriter",
        "xml",
        "xmlreader",
        "xmlrpc",
        "xmlwriter",
        "xsl",
        "xxtea",
        "yaf",
        "yaml",
        "yar",
        "zend",
        "Zend OPcache",
        "ZendCache",
        "ZendDebugger",
        "ZendUtils",
        "zip",
        "zlib",
        "zmq",
        "zookeeper",
        "zstd"
      }
    }
  }
}
